### ISSUE TITLE
Roadmap for ethers-gleam

### ISSUE THREAD

**Issue by chainvisions** [OwO-Capital/ethers-gleam#1]
Laying out of a roadmap for new features as a goal for building ``ethers-gleam`` to a state where it is useable and similar to the likes of ``ethers.js`` and ``ethers-rs``:

### Providers
- [ ]  IPC provider
- [ ]  Alchemy & Infura providers
- [ ]  Generalize the typing of parameters for ``JsonRpcCall`` and the results for ``JsonRpcResponse`` to support RPC methods that take in parameters that are different than strings or results that are objects (e.g ``eth_getBlockByNumber``)
- [ ] Add methods for submitting transactions (additional: Add optional feature (likely part of signer) for generating EIP-2930 access lists for the transaction via ``eth_createAccessList`` and submitting with the addition of the access list)
- [ ] ``eth_call`` support
- [ ] Additional block fetching methods support
- [ ] Custom block tags for methods for archiving

### Signers
- [ ] General signing transactions and messages
- [ ] Special type for connecting signer to provider
- [ ] Support for signing smart contract calls
- [ ] Middleware? (Not sure if doable in a functional context also)

###  Contracts
- [ ] Support for calling smart contracts and a new type for contracts
- [ ] Connecting to providers or signers and support for signing and encoding calls to contracts
- [ ] Multicall (as a first class citizen)
- [ ]  Endgame: Event logs

### Misc
- [ ] Utils for tasks such as generating private keys, formatting units, zero address, etc
- [ ] Modularize the JSON-RPC code used for ``JsonRpcProvider`` so that it can be reused anywhere. Ideally it would be published in [``arrpc``](https://github.com/OwO-Capital/arrpc)
- [ ] Building out example use-cases for ``ethers-gleam``

Some of these may not see their implementation until way later down on the road but my goal is to at least get basic provider, signer, and contract support going to where its somewhat useable. Things like event logs are something I can also consider wayyy later.
